# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d29465656d5eeed27548d14c4f68cc164598b384d8a29752679f840032cbf71b439ff0739353872eeb99be229ac730c3319f75ef5e27cc2f995aa7d8b334c1b5

test:
  secret_key_base: 5aa06a35c345cacd9052e165bba93c7936a6c9b026462134c78efdbd0ee455451094d7b66ac2eea58b77f869984b68494e63aff9eaf71f3d31ea563b0582de41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
